"""O'Pip Intelligence Committee plane.

MEASUREMENT ONLY - NO PRODUCTION DECISION AUTHORITY.

The Intelligence Committee obtains, preserves, evaluates, and learns from
independent model opinions. It is shadow-only, read-only, and non-authoritative.

What this plane structurally cannot do:

* place, modify, resize, or cancel an order;
* admit or reserve capital;
* change a risk limit, protection level, or forced exit;
* activate Paper v2 or alter funded/live state;
* promote a model, strategy, or threshold;
* influence production ranking, alerts, or execution by any path.

A committee result is research evidence. A model emitting an opinion never makes
that opinion canonical trading truth, and no downstream consumer may treat an
aggregate of opinions as an instruction.

The plane extends the frozen ``app.opip.decision_intelligence`` contracts rather
than replacing them, and depends on them only for canonical vocabulary
(``Provenance``, content-derived identity, canonical serialization).
"""

from __future__ import annotations

from app.opip.committee.attribution import (
    ATTRIBUTION_METHOD_VERSION,
    AttributionCase,
    AttributionReport,
    BaselineRelation,
    CONFIDENCE_SPREAD_THRESHOLD,
    CaseTypeAccuracy,
    CommitteeIncrement,
    DisagreementKind,
    DisagreementMatrix,
    DisagreementSummary,
    MIN_ATTRIBUTION_SAMPLES,
    ProviderAttribution,
    SeatVerdict,
    WindowAccuracy,
    advisory_disposition,
    baseline_relation,
    build_attribution_report,
    build_disagreement_matrix,
    committee_research_call,
)
from app.opip.committee.contracts import (
    CanonicalDecisionBinding,
    CallReplayRejection,
    CaseType,
    CommitteeCase,
    CommitteeCaseOutcome,
    CommitteePolicy,
    CostCompleteness,
    DirectionalAssessment,
    EvaluationPhase,
    EvidenceItem,
    EvidenceSnapshot,
    EvidenceSufficiency,
    ObservationStatus,
    ProviderCallOutcome,
    ProviderFailureClass,
    ProviderFamily,
    ReproducibilityClass,
    ResearchAction,
    StructuredOpinion,
    logical_observation_id,
)
from app.opip.committee.evidence import (
    EvidencePolicyError,
    build_evidence_item,
    build_evidence_snapshot,
)
from app.opip.committee.evaluation import (
    ADEQUACY_ADEQUATE,
    ADEQUACY_INSUFFICIENT_SAMPLE,
    ArmEvaluation,
    ArmKind,
    BaselineCall,
    CaseObservation,
    DirectionalCall,
    EvaluationReport,
    MIN_EVALUATION_SAMPLES,
    ProbabilityForecast,
    ReplayComparison,
    ResolvedOutcome,
    committee_research_signal,
    directional_call,
    evaluate_model_bake_off,
)
from app.opip.committee.ledger import (
    InMemoryObservationLedger,
    ObservationLedger,
)
from app.opip.committee.metrics import (
    CalibrationBin,
    CalibrationReport,
    ClassificationReport,
    ConfusionMatrix,
    CostAggregate,
    EvaluationMetric,
    LatencyDistribution,
    ProbabilitySample,
    brier_score,
    calibration_report,
    classification_report,
    confusion_matrix,
    cost_aggregate,
    latency_distribution,
    log_loss,
    repeatability_metric,
)
from app.opip.committee.pricing import (
    COMMITTEE_PRICES_ENV,
    MICROUNITS_PER_UNIT,
    TOKENS_PER_PRICING_UNIT,
    PriceBook,
    PriceBookConfigError,
    TokenPrice,
    scale_tokens,
)
from app.opip.committee.opinion import OpinionParseError, parse_structured_opinion
from app.opip.committee.outbound import OutboundPolicyError, screen_model_bound_view
from app.opip.committee.prospective import (
    HindsightLeakageError,
    OutcomeFinality,
    OutcomeObservation,
    ProspectiveEvaluation,
    ProspectivePolicyError,
    ProspectiveSeatScore,
    SealedPrediction,
    assert_outcome_is_prospective,
    awaiting_evaluation,
    awaiting_outcome,
    evaluate_prospective,
    prospective_observability_counts,
    seal_prediction,
    verify_seal,
)
from app.opip.committee.providers import (
    CommitteeProvider,
    ProviderAvailability,
    ProviderInvocationError,
    ProviderRawResponse,
    ProviderTransport,
    ProviderWireRequest,
    TransportBackedProvider,
    UnavailableProvider,
)
from app.opip.committee.runtime import (
    COMMITTEE_SYSTEM_PROMPT,
    CommitteePolicyViolation,
    CommitteeReplayDivergenceError,
    CommitteeRunResult,
    CommitteeRunner,
    CommitteeSeatResult,
)
from app.opip.committee.role_execution import (
    RoleBudget,
    RoleBudgetViolation,
    RoleResultStatus,
    RoleSeatResult,
    assert_evidence_refs_are_supported,
    assert_no_action_fields,
    role_status_for_observation,
)
from app.opip.committee.role_router import (
    MAX_ROLE_ATTEMPTS,
    RETRYABLE_ROLE_FAILURE_CLASSES,
    RoleAttempt,
    RoleExecution,
    RoleRouter,
    RoleRoutingError,
)
from app.opip.committee.roles import (
    OPTIONAL_ROLES,
    REQUIRED_ROLES,
    CommitteeRole,
    CommitteeRoleSpec,
    RoleRequirement,
    RoleSpecSet,
    default_role_spec_set,
)
from app.opip.committee.registry import (
    ApprovalState,
    ModelRegistry,
    ModelRegistryEntry,
    ReasoningMode,
    RegistryError,
    RoleRoute,
    assert_result_served_by_route,
)
from app.opip.committee.serialization import (
    CommitteeSerializationError,
    call_outcome_from_dict,
    call_outcome_to_dict,
    case_outcome_from_dict,
    case_outcome_to_dict,
    opinion_from_dict,
    opinion_to_dict,
)
from app.opip.committee.scheduler import (
    HELD_DISPOSITIONS,
    MODE_DISABLED,
    SELECTED_DISPOSITIONS,
    CommitteeScheduleDisposition,
    CommitteeScheduler,
    CommittedEvidenceItem,
    PopulationTally,
    ScheduleDispositionRecord,
    ScheduleKey,
    SchedulerBudget,
    SchedulerCheckpoint,
    SchedulerCursor,
    SchedulerError,
    SchedulerRun,
)
from app.opip.committee.store import (
    COMMITTEE_DIR,
    CommitteeEvidenceStore,
    DurableObservationLedger,
    StoreAppendResult,
)

#: Declared here so an architecture check can assert non-authority without
#: importing the runtime.
AUTHORITATIVE = False
CAN_PLACE_ORDERS = False
MEASUREMENT_ONLY = True

__all__ = [
    "ADEQUACY_ADEQUATE",
    "ADEQUACY_INSUFFICIENT_SAMPLE",
    "ATTRIBUTION_METHOD_VERSION",
    "AUTHORITATIVE",
    "ArmEvaluation",
    "ArmKind",
    "AttributionCase",
    "AttributionReport",
    "BaselineCall",
    "BaselineRelation",
    "CAN_PLACE_ORDERS",
    "COMMITTEE_DIR",
    "COMMITTEE_PRICES_ENV",
    "COMMITTEE_SYSTEM_PROMPT",
    "CONFIDENCE_SPREAD_THRESHOLD",
    "CaseObservation",
    "CaseType",
    "CaseTypeAccuracy",
    "CalibrationBin",
    "CalibrationReport",
    "CanonicalDecisionBinding",
    "CallReplayRejection",
    "ClassificationReport",
    "CommitteeRole",
    "CommitteeRoleSpec",
    "ModelRegistry",
    "ModelRegistryEntry",
    "ApprovalState",
    "ReasoningMode",
    "RegistryError",
    "RoleBudget",
    "RoleBudgetViolation",
    "CommitteeScheduleDisposition",
    "CommitteeScheduler",
    "CommittedEvidenceItem",
    "PopulationTally",
    "ScheduleDispositionRecord",
    "ScheduleKey",
    "SchedulerBudget",
    "SchedulerCheckpoint",
    "SchedulerCursor",
    "SchedulerError",
    "SchedulerRun",
    "HELD_DISPOSITIONS",
    "SELECTED_DISPOSITIONS",
    "MODE_DISABLED",
    "RoleAttempt",
    "RoleExecution",
    "RoleRouter",
    "RoleRoutingError",
    "RETRYABLE_ROLE_FAILURE_CLASSES",
    "MAX_ROLE_ATTEMPTS",
    "RoleRequirement",
    "RoleResultStatus",
    "RoleRoute",
    "RoleSeatResult",
    "RoleSpecSet",
    "OPTIONAL_ROLES",
    "REQUIRED_ROLES",
    "assert_evidence_refs_are_supported",
    "assert_no_action_fields",
    "assert_result_served_by_route",
    "default_role_spec_set",
    "role_status_for_observation",
    "CommitteeCase",
    "CommitteeCaseOutcome",
    "CommitteeEvidenceStore",
    "CommitteeIncrement",
    "CommitteePolicy",
    "CommitteePolicyViolation",
    "CommitteeProvider",
    "CommitteeReplayDivergenceError",
    "CommitteeRunResult",
    "CommitteeRunner",
    "CommitteeSeatResult",
    "CommitteeSerializationError",
    "ConfusionMatrix",
    "CostAggregate",
    "CostCompleteness",
    "DirectionalAssessment",
    "DirectionalCall",
    "DisagreementKind",
    "DisagreementMatrix",
    "DisagreementSummary",
    "DurableObservationLedger",
    "EvaluationMetric",
    "EvaluationPhase",
    "EvaluationReport",
    "EvidenceItem",
    "EvidencePolicyError",
    "EvidenceSnapshot",
    "EvidenceSufficiency",
    "HindsightLeakageError",
    "InMemoryObservationLedger",
    "LatencyDistribution",
    "MEASUREMENT_ONLY",
    "MICROUNITS_PER_UNIT",
    "MIN_EVALUATION_SAMPLES",
    "MIN_ATTRIBUTION_SAMPLES",
    "ObservationLedger",
    "ObservationStatus",
    "OpinionParseError",
    "OutboundPolicyError",
    "OutcomeFinality",
    "OutcomeObservation",
    "PriceBook",
    "PriceBookConfigError",
    "ProbabilityForecast",
    "ProbabilitySample",
    "ProspectiveEvaluation",
    "ProspectivePolicyError",
    "ProspectiveSeatScore",
    "ProviderAvailability",
    "ProviderCallOutcome",
    "ProviderFailureClass",
    "ProviderFamily",
    "ProviderInvocationError",
    "ProviderRawResponse",
    "ProviderTransport",
    "ProviderWireRequest",
    "ProviderAttribution",
    "ReplayComparison",
    "ReproducibilityClass",
    "ResearchAction",
    "ResolvedOutcome",
    "SealedPrediction",
    "SeatVerdict",
    "StoreAppendResult",
    "StructuredOpinion",
    "TOKENS_PER_PRICING_UNIT",
    "TokenPrice",
    "TransportBackedProvider",
    "UnavailableProvider",
    "WindowAccuracy",
    "advisory_disposition",
    "assert_outcome_is_prospective",
    "awaiting_evaluation",
    "awaiting_outcome",
    "baseline_relation",
    "brier_score",
    "build_attribution_report",
    "build_disagreement_matrix",
    "build_evidence_item",
    "build_evidence_snapshot",
    "calibration_report",
    "call_outcome_from_dict",
    "call_outcome_to_dict",
    "case_outcome_from_dict",
    "case_outcome_to_dict",
    "classification_report",
    "committee_research_call",
    "committee_research_signal",
    "confusion_matrix",
    "cost_aggregate",
    "directional_call",
    "evaluate_model_bake_off",
    "evaluate_prospective",
    "latency_distribution",
    "log_loss",
    "logical_observation_id",
    "opinion_from_dict",
    "opinion_to_dict",
    "parse_structured_opinion",
    "prospective_observability_counts",
    "repeatability_metric",
    "scale_tokens",
    "screen_model_bound_view",
    "seal_prediction",
    "verify_seal",
]
